mode = "dark"

accent = "#82aaff"
selection = "#1d3b53"
muted = "#575656"

background = "#011627"
dark_background = "#01111d"
darker_background = "#010b14"
lighter_background = "#0b2942"

foreground = "#d6deeb"
dark_foreground = "#575656"
light_foreground = "#d6deeb"
bright_foreground = "#ffffff"

red = "#ef5350"
yellow = "#c5e478"
orange = "#f78c6c"
green = "#22da6e"
cyan = "#21c7a8"
blue = "#82aaff"
magenta = "#c792ea"
brown = "#63723c"

bright_red = "#ef5350"
bright_yellow = "#ffeb95"
bright_green = "#22da6e"
bright_cyan = "#7fdbca"
bright_blue = "#82aaff"
bright_magenta = "#c792ea"
