$activeBorderColor = rgb(82aaff)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    blur {
        enabled = true
        size = 6
        passes = 3
        contrast = 1.5
        brightness = 0.8
        vibrancy = 0.2
        vibrancy_darkness = 0.2
        noise = 0.07
        ignore_opacity = true
        new_optimizations = on
    }
    active_opacity = 0.98
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0
}

layerrule {
    name = blur_with_ignore_alpha
    match:namespace = ^(walker|notifications|swayosd|waybar)$
    blur = true
    ignore_alpha = 0.1
}
